
export const ACTIONS = {
    CUSTOMERS_LIST_FETCHED: "CUSTOMERS_LIST_FETCHED",
    CUSTOMER_DIGEST_FETCHED: "CUSTOMER_DIGEST_FETCHED",
    CUSTOMER_DIGEST_FETCH_INITIATED: "CUSTOMER_DIGEST_FETCH_INITIATED",
    CHANGE_ACTIVE_STATE: "CHANGE_ACTIVE_STATE",
    SET_PAGE_SIZE: "SET_PAGE_SIZE",
    SET_PAGE_INDEX: "SET_PAGE_INDEX",
    SORT_DATA: "SORT_DATA",
    CUSTOMER_UPDATED: "CUSTOMER_UPDATED"
};